@startuml

!theme plain
skinparam dpi 300

actor "Human" as client
participant "Arduino" as arduino
participant "Unity" as unity

client -> arduino: motion input
arduino -> arduino: callculate angles
arduino -> unity: send angles to unity
@enduml