@startuml connect

!theme plain
skinparam dpi 500

!pragma teoz true
actor       "Human"             as client
box         "Arduino Nano33BLE" #LightBlue
box         "nRF52"             #LightCyan
participant "Main"              as main
end box
end box
participant "Demo Game"         as game

client -> game: connect(baudrate,portname)
game -> game: AccessSerialPort()
game -> main: Setup()
main -> main: inititalizeGyroscope()
main --> game: Calibration Steps
game -> game: DisplaySerial()
loop
main -> main: calculateAngles()
main -> main: sendDataFrame()
main --> game: Frame
game -> game: DisplaySerial()
end
game --> client: connectionState()
main -> game: send initialyzing state
@enduml