@startuml connect

!theme plain
skinparam dpi 500

!pragma teoz true
actor       "Human"             as client
box         "Arduino Nano33BLE" #LightBlue
box         "nRF52"             #LightCyan
participant "Main"              as main
end box
end box
participant "Demo Game"         as game

client -> game: connect()
game -> game: establishSerialConnection()
game --> client: connectionState()
main -> main: inititalizeGyroscope()
main -> game: send initialyzing state
@enduml