@startuml

!theme plain
skinparam dpi 300

!pragma teoz true
actor       "Human"             as client
box         "Arduino Nano33BLE" #LightBlue
participant "Sensors"           as sensors
box         "nRF52"             #LightCyan
participant "Main"              as main
participant "PID Controller"    as pid
participant "Protocol Handler"  as protocol
end box
end box
participant "Demo Game"         as game

client    ->    sensors:    motion input
main      ->    sensors:    getSensorData()
sensors   -->   main:       GyroData
sensors   -->   main:       AccelData
main      ->    main:       Check Accel > 1G
'=============================================
alt Accel > 1G  
main      ->    pid:        ProcesError(GyroData, TimeDelta)  
'--------------------------------------------
else Accel < 1G
main      ->    main:       calculateAnglesFromAccel()
main      ->    main:       calculateError()
main      ->    pid:        ProcesError(AngleError, TimeDelta)  
end
'============================================
pid       ->    pid:        ProcessError()
pid       -->   main:       AngleCorrection
main      ->    main:       correct current angles
main      ->    protocol:   sendDataFrame(angles, acceleration)
protocol  ->    protocol:   create frame
protocol  -->   game:       frame
game      ->    game:       interpret frame
game      ->    game:       rotate drone
game      ->    game:       move drone

@enduml